extend type Query {
  "Get logged-in user's data"
  user: User!
  login(email: String!, password: String!): UserResponse!
}

type UserResponse {
  code: String!
  success: Boolean!
  error: String
  data: User
  "Authentication token"
  token: String
}

type User {
  _id: ID!
  email: String
  name: String
}
